### ISSUE TITLE
Slope Movement is buggy?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#63]
I have an entity that extends the Player entity.

I haven't done much customization yet and I notice when my character is moving DOWN on slopes, he falls on and off the slop constantly causing my dude to switch animation from running to falling rapidly.

This does not happen on regular impact entities, what's going on?

**Comment by collinhover** [comment]
Currently entities don't stick to slopes. Originally I was checking for slopes and modifying the velocity to be parallel to the slope, but this was not playing nice with impact's collision map tracing. On the other hand, running up slopes with impact's original handling would cause characters to fly up into the air. Now, when moving up slopes, characters move slower and a bit of velocity is added so you can customize how tough running up feels. And for moving down, the character has a short customizable delay before the falling animation kicks in (see `ig.Character.updateCurrentAnim`) so that the animation flipping issue you're describing doesn't occur. Additionally, I believe in original impact the gravity is always being applied, while in impact++ it may only be applied while the entity is ungrounded, so you've got to go off the slope to fall back onto it. This may be something to change...

That said, I would prefer characters stick to slopes. The changes impact++ institutes are done in the `handleMovementTrace` method of `ig.EntityExtended` and `ig.Character` if you want to play with or restore the original behavior.

**Comment by arakash92** [comment]
Ok, thanks. I'll take a look at it!

Another thing too is that I'm playing a footsteps sound while my character is walking/running so it's important that the `grounded` property stay true at all times while walking on the slope.

**Comment by collinhover** [comment]
The grounded property is something I added to entities because the original standing property is not stable, i.e. it constantly switches. I think you can make your character stick to slopes by always setting them to always have max gravity except when jumping. However, this will have the side effect of sliding down slopes, so you will need to decide which is best. If you have a better solution, please let me know.

In the case of the sound, why not play the sound based on what animation is playing?

**Comment by arakash92** [comment]
I guess tying sounds to the animation is a good idea.

How would I make the character always have gravity though?

**Comment by collinhover** [comment]
So I went ahead and tested a few things, and there is actually a bug that is causing the idle animation to play instead of the movement (run) animation if the character is in the air but not yet falling. Thanks for pushing me to check :-)

Also, while I was at it I decided to try to make characters sticky, and got it working nicely. Currently my internet is down, but once it comes back up I'll push these updates to github and close this issue.

**Comment by arakash92** [comment]
Awesome! ;D

**Comment by collinhover** [comment]
Try with latest dev branch please. Does it behave as expected?

**Comment by arakash92** [comment]
Gonna test it now :P

**Comment by arakash92** [comment]
Works great, thanks! ;D

**Comment by arakash92** [comment]
Hm, I noticed a bug. Sometimes when I land on slopes, my character 'flickers' back and forth from grounded and non-grounded.

Can you check if it happens for you as well?

**Comment by collinhover** [comment]
When you say flickers, do you mean the grounded property is changing between true and false constantly on the slope?

**Comment by arakash92** [comment]
Yes :P

**Comment by collinhover** [comment]
I'll take a look.

**Comment by collinhover** [comment]
I can't find any situations where the entity is switching between grounded true/false more than once on a slope, and the only time this happens is when I stand on a slope, jump, and land on the slope. That said, I've made a minor change to the movement handling which may fix your issue. Can you try again with the latest dev branch? If it still happens, can you take a screen shot of the game when it happens?

**Comment by arakash92** [comment]
Hm ok. Maybe I should try creating a stripped down player entity and make sure it's not something that I'm doing.

I'll try the new commit as well.

Yes, in fact I'll do a quick screen recording.
Thanks again for helping! Hopefully I'm helping a bit as well :smile:

**Comment by arakash92** [comment]
Here's a video of the bug http://www.screenr.com/W3kH

I'm gonna try your new commit now.

**Comment by arakash92** [comment]
I tried your new commit, I got less 'falls' with that one but it's not fixed.

**Comment by collinhover** [comment]
Interesting, thanks for the video explanation and for pointing out 2 bugs so far! I think I know what is going on, but I need to run some more tests tomorrow to be sure.

**Comment by arakash92** [comment]
Great, no problem :)

**Comment by arakash92** [comment]
I have another observation: When landing on a slope with a X velocity other than zero does not make the bug occur.

**Comment by collinhover** [comment]
Okay, the latest commit fixes the issue of the grounded state when jumping on a slope + some other cases I could find. In original ImpactJS, you slide down slopes by default, and the issue is that if you don't want characters to slide down when standing still on a slope, sometimes you need to ignore the collision map position result. Unfortunately, this can cause the character to stop being grounded for 1 frame, but this case is fixed.

On most slopes the grounded state remains constant, but occasionally on a 45 degree angled slope the character will change grounded a few times because of the steep angle. I don't think handling this particular case is worth it, instead I've added a `falling` property to characters that will be set to true if a character is not grounded for a duration above `ungroundedForAndFallingThreshold`.

**Comment by arakash92** [comment]
nice :)

**Comment by arakash92** [comment]
Seems to me that the bug still occurs?

**Comment by arakash92** [comment]
Ah, so with the new falling property, it does work! ;D

**Comment by arakash92** [comment]
Actually I'm still getting the bug. the 'faling' property seems to always be false?
